### ISSUE TITLE
Getting a `'NoneType' object has no attribute 'getText'`

### ISSUE THREAD

**Issue by ni-dschiller** [CMakePP/CMinx#70] opened 2022-06-08 15:59 UTC
``` bash
Traceback (most recent call last):

  File "/Volumes/build/jenkins-build/35012f-0/.venv/bin/cminx", line 33, in <module>

    sys.exit(load_entry_point('CMinx==1.0.0', 'console_scripts', 'cminx')())

  File "/Volumes/build/jenkins-build/35012f-0/.venv/lib/python3.9/site-packages/CMinx-1.0.0-py3.9.egg/cminx/__init__.py", line 70, in main

  File "/Volumes/build/jenkins-build/35012f-0/.venv/lib/python3.9/site-packages/CMinx-1.0.0-py3.9.egg/cminx/__init__.py", line 125, in document

  File "/Volumes/build/jenkins-build/35012f-0/.venv/lib/python3.9/site-packages/CMinx-1.0.0-py3.9.egg/cminx/__init__.py", line 166, in document_single_file

  File "/Volumes/build/jenkins-build/35012f-0/.venv/lib/python3.9/site-packages/CMinx-1.0.0-py3.9.egg/cminx/documenter.py", line 67, in __init__

  File "/Volumes/build/jenkins-build/35012f-0/.venv/lib/python3.9/site-packages/antlr4_python3_runtime-4.7.2-py3.9.egg/antlr4/tree/Tree.py", line 151, in walk

    self.walk(listener, child)

  File "/Volumes/build/jenkins-build/35012f-0/.venv/lib/python3.9/site-packages/antlr4_python3_runtime-4.7.2-py3.9.egg/antlr4/tree/Tree.py", line 149, in walk

    self.enterRule(listener, t)

  File "/Volumes/build/jenkins-build/35012f-0/.venv/lib/python3.9/site-packages/antlr4_python3_runtime-4.7.2-py3.9.egg/antlr4/tree/Tree.py", line 163, in enterRule

    ctx.enterRule(listener)

  File "/Volumes/build/jenkins-build/35012f-0/.venv/lib/python3.9/site-packages/CMinx-1.0.0-py3.9.egg/cminx/parser/CMakeParser.py", line 188, in enterRule

  File "/Volumes/build/jenkins-build/35012f-0/.venv/lib/python3.9/site-packages/CMinx-1.0.0-py3.9.egg/cminx/parser/aggregator.py", line 469, in enterCommand_invocation

  File "/Volumes/build/jenkins-build/35012f-0/.venv/lib/python3.9/site-packages/CMinx-1.0.0-py3.9.egg/cminx/parser/aggregator.py", line 142, in process_macro

  File "/Volumes/build/jenkins-build/35012f-0/.venv/lib/python3.9/site-packages/CMinx-1.0.0-py3.9.egg/cminx/parser/aggregator.py", line 142, in <listcomp>

AttributeError: 'NoneType' object has no attribute 'getText'

script returned exit code 1
```

**Comment by ryanmrichard** [comment] 2022-06-08 16:17
Any chance you can post a minimum working example which generates this error?

**Comment by ni-dschiller** [comment] 2022-06-08 16:20
THat's pretty hard as it is inside of our Jenkins CI Pipeline. I believe it has something todo with the Python Version possibly. What exact data would help ?

**Comment by ni-dschiller** [comment] 2022-06-08 16:28
How can I find out which file it is ? I thought it's the last line above the Traceback but there is only the info about the converted `.rst`: 

<img width="1091" alt="Screenshot 2022-06-08 at 18 27 09" src="https://user-images.githubusercontent.com/91887263/172668834-b78eb6ea-d9c3-4925-ae39-a068483996dd.png">

**Comment by AutonomicPerfectionist** [comment] 2022-06-08 16:34
@ni-dschiller @ryanmrichard it appears CMinx encountered a documented macro definition that has a non-literal parameter. This is usually due to attempting to dynamically define a macro name like `macro(${a_name})` but in this instance it was a different parameter. Using dynamically assigned parameter identifiers is not currently supported. As for which file it is, check the next `.cmake` file in alphabetical order succeeding the one that is second-to-last in the output before the traceback. I will have to adjust the output so that the "Writing for file" lines are printed before attempting to parse in the future

**Comment by ni-dschiller** [comment] 2022-06-08 16:38
Interestingly when I run CMinx locally with the same branch / files ( CMake ) then it works without any issues.

Because of that I thought maybe they way of installing CMinx is problematic. They way how I feed the Jenkins stage is:

```
...
               checkout(
                    directory: 'CMinx',
                    url: 'https://github.com/CMakePP/CMinx',
                    gitReference: 'master'
                )
...
                    // Build and install CMinx
                    exec(cmd: "cd CMinx && python setup.py install")

                    // Generate the `rst` files with CMinx
                    exec(cmd: "cd docs && cminx -o docs -r ../cmake-files")
```

**Comment by AutonomicPerfectionist** [comment] 2022-06-08 16:53
It can be done with some additional checks and processing, however I'm unsure how to display such signatures in the documentation, since Python has no analog to that. I can look into manual linking to the referenced variables

**Comment by ni-dschiller** [comment] 2022-06-08 16:56
Was thinking the same as Ryan.

For the moment a quick solution could be to remove the DocStrings for those macros and functions.

**Comment by ni-dschiller** [comment] 2022-06-08 17:07
Exactly Ryan! I am still struggling with finding out the exact line in the next CMake file which produces this hiccup but I can not find any function or macro with a dynamic signature or name.

**Comment by ni-dschiller** [comment] 2022-06-08 17:18
I couldn't find any following file which has a DocString `#[[[` and a dynamic name or signature for `function`, `set` or `macro`.

**Comment by ryanmrichard** [comment] 2022-06-08 17:20
FWIW with @AutonomicPerfectionist's newest change it should print out the file causing the error, so that should help narrow it down.

**Comment by ni-dschiller** [comment] 2022-06-08 17:22
The only thing I found are some `set`'s and `macro`'s without any DocStrings but I guess they are not parsed as I understand.

```
macro( my_macro ${Target} )
...

```

**Comment by ni-dschiller** [comment] 2022-06-08 17:28
> FWIW with @AutonomicPerfectionist's newest change it should print out the file causing the error, so that should help narrow it down.
> 
> Edit: I was referring to #73

It's merged to master right ? I just rerun my Jenkins Job and checked out the latest CMinx master but don't see a difference.

```
Writing RST file /Volumes/build/jenkins-build/35012f-0/docs/docs/any_cmake_file.rst
Traceback (most recent call last):
  File "/Volumes/build/jenkins-build/35012f-0/.venv/bin/cminx", line 33, in <module>
    sys.exit(load_entry_point('CMinx==1.0.0', 'console_scripts', 'cminx')())
  File "/Volumes/build/jenkins-build/35012f-0/.venv/lib/python3.9/site-packages/CMinx-1.0.0-py3.9.egg/cminx/__init__.py", line 70, in main
  File "/Volumes/build/jenkins-build/35012f-0/.venv/lib/python3.9/site-packages/CMinx-1.0.0-py3.9.egg/cminx/__init__.py", line 125, in document
  File "/Volumes/build/jenkins-build/35012f-0/.venv/lib/python3.9/site-packages/CMinx-1.0.0-py3.9.egg/cminx/__init__.py", line 166, in document_single_file
  File "/Volumes/build/jenkins-build/35012f-0/.venv/lib/python3.9/site-packages/CMinx-1.0.0-py3.9.egg/cminx/documenter.py", line 67, in __init__
  File "/Volumes/build/jenkins-build/35012f-0/.venv/lib/python3.9/site-packages/antlr4_python3_runtime-4.7.2-py3.9.egg/antlr4/tree/Tree.py", line 151, in walk
    self.walk(listener, child)
  File "/Volumes/build/jenkins-build/35012f-0/.venv/lib/python3.9/site-packages/antlr4_python3_runtime-4.7.2-py3.9.egg/antlr4/tree/Tree.py", line 149, in walk
    self.enterRule(listener, t)
  File "/Volumes/build/jenkins-build/35012f-0/.venv/lib/python3.9/site-packages/antlr4_python3_runtime-4.7.2-py3.9.egg/antlr4/tree/Tree.py", line 163, in enterRule
    ctx.enterRule(listener)
  File "/Volumes/build/jenkins-build/35012f-0/.venv/lib/python3.9/site-packages/CMinx-1.0.0-py3.9.egg/cminx/parser/CMakeParser.py", line 188, in enterRule
  File "/Volumes/build/jenkins-build/35012f-0/.venv/lib/python3.9/site-packages/CMinx-1.0.0-py3.9.egg/cminx/parser/aggregator.py", line 469, in enterCommand_invocation
  File "/Volumes/build/jenkins-build/35012f-0/.venv/lib/python3.9/site-packages/CMinx-1.0.0-py3.9.egg/cminx/parser/aggregator.py", line 142, in process_macro
  File "/Volumes/build/jenkins-build/35012f-0/.venv/lib/python3.9/site-packages/CMinx-1.0.0-py3.9.egg/cminx/parser/aggregator.py", line 142, in <listcomp>
AttributeError: 'NoneType' object has no attribute 'getText'
```

**Comment by ni-dschiller** [comment] 2022-06-08 17:29
Do I need to use the Verbose switch ?

**Comment by ryanmrichard** [comment] 2022-06-08 17:30
It's merged. He just moved where the print statement was (so no verbose yet). @AutonomicPerfectionist does his log mean the problem is in `any_cmake_file.cmake` ?

**Comment by ni-dschiller** [comment] 2022-06-08 17:42
I think it seems not to work `Move log output to before parsing (#73)` I tried it locally by provoking the error with:

#### invalid_file.cmake
```
function(my_func ${Target})
...
```

Making sure the latest Changes in place:

```
CMinx % git log
commit b86a24615a2bb57ba33d7bd770ddd78ebda1716b (HEAD -> master, origin/master, origin/HEAD)
Author: Branden Butler <bwtbutler@hotmail.com>
Date:   Wed Jun 8 11:57:07 2022 -0500

    Move log output to before parsing (#73)

...
```

And running CMinx:

```
Writing RST file /Volumes/K2TB/Work/Coding/CMake/ni-cmake-tools-docs-x/docs/docs/valid_file.rst
Traceback (most recent call last):
  File "/Users/dirk.schiller/.pyenv/versions/3.9-dev/bin/cminx", line 8, in <module>
    sys.exit(main())
  File "/Users/dirk.schiller/.pyenv/versions/3.9-dev/lib/python3.9/site-packages/cminx/__init__.py", line 70, in main
    document(input, output_path, args.recursive, args.prefix)
  File "/Users/dirk.schiller/.pyenv/versions/3.9-dev/lib/python3.9/site-packages/cminx/__init__.py", line 120, in document
    document_single_file(os.path.join(root, file), input_path, output_path, prefix)
  File "/Users/dirk.schiller/.pyenv/versions/3.9-dev/lib/python3.9/site-packages/cminx/__init__.py", line 158, in document_single_file
    documenter = Documenter(file, header_name)
  File "/Users/dirk.schiller/.pyenv/versions/3.9-dev/lib/python3.9/site-packages/cminx/documenter.py", line 71, in __init__
    self.walker.walk(self.aggregator, self.tree)
  File "/Users/dirk.schiller/.pyenv/versions/3.9-dev/lib/python3.9/site-packages/antlr4/tree/Tree.py", line 151, in walk
    self.walk(listener, child)
  File "/Users/dirk.schiller/.pyenv/versions/3.9-dev/lib/python3.9/site-packages/antlr4/tree/Tree.py", line 149, in walk
    self.enterRule(listener, t)
  File "/Users/dirk.schiller/.pyenv/versions/3.9-dev/lib/python3.9/site-packages/antlr4/tree/Tree.py", line 163, in enterRule
    ctx.enterRule(listener)
  File "/Users/dirk.schiller/.pyenv/versions/3.9-dev/lib/python3.9/site-packages/cminx/parser/CMakeParser.py", line 264, in enterRule
    listener.enterDocumented_command(self)
  File "/Users/dirk.schiller/.pyenv/versions/3.9-dev/lib/python3.9/site-packages/cminx/parser/aggregator.py", line 205, in enterDocumented_command
    getattr(self, f"process_{command}")(ctx, cleaned_doc)
  File "/Users/dirk.schiller/.pyenv/versions/3.9-dev/lib/python3.9/site-packages/cminx/parser/aggregator.py", line 58, in process_function
    params = [param.Identifier().getText() for param in ctx.command_invocation().single_argument()[1:]] #Extract declared function parameters
  File "/Users/dirk.schiller/.pyenv/versions/3.9-dev/lib/python3.9/site-packages/cminx/parser/aggregator.py", line 58, in <listcomp>
    params = [param.Identifier().getText() for param in ctx.command_invocation().single_argument()[1:]] #Extract declared function parameters
AttributeError: 'NoneType' object has no attribute 'getText'

```

**Comment by AutonomicPerfectionist** [comment] 2022-06-08 17:43
@ryanmrichard @ni-dschiller turns out I misread the function name and put the log statement in the wrong place, I have a new PR up that actually does what it's supposed to do (#74 )

**Comment by ni-dschiller** [comment] 2022-06-08 17:47
Nice, that worked ! 🙏

**Comment by AutonomicPerfectionist** [comment] 2022-06-08 17:53
It is fairly easy actually, it'll just take a try/except block in the primary listener and a few lookups inside the context

**Comment by ni-dschiller** [comment] 2022-06-08 17:57
Thank's Branden! I'll reverse engineer the CMake file I know now to see where CMinx fails and let you know.

**Comment by ni-dschiller** [comment] 2022-06-08 18:13
I could narrow the issue and it doesn't fail on a documented macro / function. Seems something else is wrong here.

**Comment by AutonomicPerfectionist** [comment] 2022-06-08 18:29
The line number of the CMake file should be printed when an exception is caught now, in PR #75. It should be noted that for now it only prints the line number of the command that was being processed, getting an exact line/column number pair of the offending token will take much more granular error handling

**Comment by AutonomicPerfectionist** [comment] 2022-06-08 18:40
@ni-dschiller we auto-document all functions and macros, even with no doc-comments. Those without are autogenerated with basic information by inspecting the command parameters. There are two options we have at the moment: 

1. Remove the re-raise of exceptions in the handler temporarily, this will allow your documentation to continue being generated while I work on support for dynamically generated parameters.
2. Add checks in the function and macro handlers for these dynamically generated parameters and return when they are detected. This will have the same external effect as the first option

After one of these options is implemented I will begin working on support for dynamically generated parameters, as well as investigate any other possible edge cases.

@ryanmrichard what option do you think we should implement temporarily? The first would be easiest and fastest but clobbers all exceptions, the second is a little more involved but doesn't hide any other errors that might occur

**Comment by ryanmrichard** [comment] 2022-06-08 18:43
How hard would it be to add a flag controlling whether we document un-documented members? Otherwise I'd vote for option 2.

**Comment by AutonomicPerfectionist** [comment] 2022-06-08 18:50
Actually @ryanmrichard @ni-dschiller turns out in order to add support for dynamically generated parameters is as easy as removing one call in a chain. The Antlr4 documentation is not fantastic for the Python implementation so I missed that earlier. I'll need to also modify some tests that depended on dynamic parameters causing failures

As for the flag, shouldn't be too difficult to add, from what I can tell it should just be a simple propagation of a boolean down from the initial `document()` call all the way to the `DocumentationAggregator`

**Comment by ryanmrichard** [comment] 2022-06-08 18:59
@AutonomicPerfectionist I'm getting the impression we may need to have a lot of toggles. I like the idea of them being flags (which can also be set from a settings file #76), but internally we probably need a `Settings` object or something to encapsulate them. My point is let's get the dynamic parameters in first, and then think about how to do settings.

**Comment by AutonomicPerfectionist** [comment] 2022-06-08 19:20
> @AutonomicPerfectionist I'm getting the impression we may need to have a lot of toggles. I like the idea of them being flags (which can also be set from a settings file #76), but internally we probably need a `Settings` object or something to encapsulate them. My point is let's get the dynamic parameters in first, and then think about how to do settings.

I agree, a simple dictionary-based Settings object should work fairly well

**Comment by ni-dschiller** [comment] 2022-06-08 20:15
> 

Thank's a lot Branden, that worked! Now I have a new level of information regarding the File title and all those undocumented functions and methods:

<img width="1224" alt="Screenshot 2022-06-08 at 21 51 46" src="https://user-images.githubusercontent.com/91887263/172708636-5032443b-0717-47a8-bb85-9f641406e7d7.png">

**Comment by ni-dschiller** [comment] 2022-06-08 20:29
For example for undocumented `cmake` files i generate `No Ducumentation yet` notes.

<img width="1035" alt="Screenshot 2022-06-08 at 22 28 23" src="https://user-images.githubusercontent.com/91887263/172711188-14145c02-8cd7-4fe9-ba48-1ee9ef529fa9.png">

**Comment by ni-dschiller** [comment] 2022-06-08 21:18
It seems with the latest changes also the `.cmake` disappeared from the file title.

Before it was `cmake_files/my-file.cmake`:

```
# my-file.cmake
```

Now it is for the same file ( `cmake_files/my-file.cmake` ):

```
# cmake_files.my-file
```

**Comment by ni-dschiller** [comment] 2022-06-08 21:39
> > 
> 
> Thank's a lot Branden, that worked! Now I have a new level of information regarding the File title and all those undocumented functions and macros:
> 
> <img alt="Screenshot 2022-06-08 at 21 51 46" width="1224" src="https://user-images.githubusercontent.com/91887263/172708636-5032443b-0717-47a8-bb85-9f641406e7d7.png">
> 
> But I think that's nice. This way we see what's inside and I can transform those empty functions and macros with a notice that they are undocumented. Not sure if that forces us in the end to document everything even if we possibly use functions and macros which doesn't need to be documented but that's possibly another question.

Fixed the changing title and the empty functions / macros:

<img width="1207" alt="Screenshot 2022-06-08 at 23 38 03" src="https://user-images.githubusercontent.com/91887263/172722011-4121d26a-95a4-484d-90f3-52843b21d663.png">

**Comment by AutonomicPerfectionist** [comment] 2022-06-08 21:45
> It seems with the latest changes also the `.cmake` disappeared from the file title.
> 
> Before it was `cmake_files/my-file.cmake`:
> 
> ```
> # my-file.cmake
> ```
> 
> Now it is for the same file ( `cmake_files/my-file.cmake` ):
> 
> ```
> # cmake_files.my-file
> ```

@ni-dschiller that change was intentional, it caused confusion in regards to whether the `cmake` part was part of the module path or a file extension. If the file extension is desired we could possibly add it back in the title only, and replace the periods in the module path with slashes to better reflect the convention used to `include()` modules

**Comment by ni-dschiller** [comment] 2022-06-08 22:40
> > It seems with the latest changes also the `.cmake` disappeared from the file title.
> > Before it was `cmake_files/my-file.cmake`:
> > ```
> > # my-file.cmake
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Now it is for the same file ( `cmake_files/my-file.cmake` ):
> > ```
> > # cmake_files.my-file
> > ```
> 
> @ni-dschiller that change was intentional, it caused confusion in regards to whether the `cmake` part was part of the module path or a file extension. If the file extension is desired we could possibly add it back in the title only, and replace the periods in the module path with slashes to better reflect the convention used to `include()` modules

Brandon, no difference for me, I can handle both and just still change my transform Code which transforms from `.rst` CMinx to Markdown.

**Closed** 2022-06-08 23:00 UTC
Labels: question
